// ---- Created with 3Dmigoto v1.3.16 on Sun Aug 31 23:18:00 2025

SamplerState g_sampler_s : register(s0);
Texture2D<float4> g_texture : register(t0);


// 3Dmigoto declarations
#define cmp -
#include "./common1.hlsl"


void main(
  float4 v0 : SV_POSITION0,
  float4 v1 : COLOR0,
  float2 v2 : TEXCOORD0,
  out float4 o0 : SV_Target0)
{
  float4 r0,r1;
  uint4 bitmask, uiDest;
  float4 fDest;
  r0.x = g_texture.SampleLevel(g_sampler_s, v2.xy, 0, int2(-1, 0)).w;
  r0.x = max(9.99999972e-010, r0.x);
  r0.y = g_texture.SampleLevel(g_sampler_s, v2.xy, 0, int2(1, 0)).w;
  r0.x = max(r0.x, r0.y);
  r0.y = g_texture.SampleLevel(g_sampler_s, v2.xy, 0, int2(0, -1)).w;
  r0.x = max(r0.x, r0.y);
  r0.y = g_texture.SampleLevel(g_sampler_s, v2.xy, 0, int2(0, 1)).w;
  r0.x = max(r0.x, r0.y);
  r0.w = g_texture.SampleLevel(g_sampler_s, v2.xy, 0, int2(-2, 0)).w;
  r0.w = max(9.99999972e-010, r0.w);
  r1.x = g_texture.SampleLevel(g_sampler_s, v2.xy, 0, int2(2, 0)).w;
  r0.w = max(r1.x, r0.w);
  r1.x = g_texture.SampleLevel(g_sampler_s, v2.xy, 0, int2(0, -2)).w;
  r0.w = max(r1.x, r0.w);
  r1.x = g_texture.SampleLevel(g_sampler_s, v2.xy, 0, int2(0, 2)).w;
  r0.y = max(r1.x, r0.w);
  r0.w = g_texture.SampleLevel(g_sampler_s, v2.xy, 0, int2(-1, -1)).w;
  r0.w = max(9.99999972e-010, r0.w);
  r1.x = g_texture.SampleLevel(g_sampler_s, v2.xy, 0, int2(1, -1)).w;
  r0.w = max(r1.x, r0.w);
  r1.x = g_texture.SampleLevel(g_sampler_s, v2.xy, 0, int2(-1, 1)).w;
  r0.w = max(r1.x, r0.w);
  r1.x = g_texture.SampleLevel(g_sampler_s, v2.xy, 0, int2(1, 1)).w;
  r0.z = max(r1.x, r0.w);
  r0.xyz = float3(0.899999976, 0.600000024, 0.800000012) * r0.xyz;

  r0.w = g_texture.SampleLevel(g_sampler_s, v2.xy, 0).w;
  r1.xyz = v1.xyz * r0.www;
  r1.xyz = v1.www * r1.xyz;
  
  r0.x = max(r0.x, max(r0.w, 0));  // disasm instr 29: max r0.x, r0.x, r1.x (center alpha)
  r0.x = max(r0.x, r0.y);
  r0.x = max(r0.x, r0.z);
  o0.xyz = r0.x > 0 ? r1.xyz / r0.x : 0;
  o0.w = v1.w * r0.x;
  
  o0.xyz = max(0, o0.xyz);
  o0.w = saturate(o0.w);

  return;
}

// //
// // Generated by Microsoft (R) HLSL Shader Compiler 10.1
// //
// //
// // Resource Bindings:
// //
// // Name                                 Type  Format         Dim      HLSL Bind  Count
// // ------------------------------ ---------- ------- ----------- -------------- ------
// // g_sampler                         sampler      NA          NA             s0      1 
// // g_texture                         texture  float4          2d             t0      1 
// //
// //
// //
// // Input signature:
// //
// // Name                 Index   Mask Register SysValue  Format   Used
// // -------------------- ----- ------ -------- -------- ------- ------
// // SV_POSITION              0   xyzw        0      POS   float       
// // COLOR                    0   xyzw        1     NONE   float   xyzw
// // TEXCOORD                 0   xy          2     NONE   float   xy  
// //
// //
// // Output signature:
// //
// // Name                 Index   Mask Register SysValue  Format   Used
// // -------------------- ----- ------ -------- -------- ------- ------
// // SV_Target                0   xyzw        0   TARGET   float   xyzw
// //
//       0x00000000: ps_5_0
//       0x00000008: dcl_globalFlags refactoringAllowed
//       0x0000000C: dcl_sampler s0, mode_default
//       0x00000018: dcl_resource_texture2d (float,float,float,float) t0
//       0x00000028: dcl_input_ps linear v1.xyzw
//       0x00000034: dcl_input_ps linear v2.xy
//       0x00000040: dcl_output o0.xyzw
//       0x0000004C: dcl_temps 2
//    0  0x00000054: sample_l_aoffimmi_indexable(-1,0,0)(texture2d)(float,float,float,float) r0.x, v2.xyxx, t0.wxyz, s0, l(0.000000)
//    1  0x0000008C: max r0.x, r0.x, l(0.000000)
//    2  0x000000A8: sample_l_aoffimmi_indexable(1,0,0)(texture2d)(float,float,float,float) r0.y, v2.xyxx, t0.xwyz, s0, l(0.000000)
//    3  0x000000E0: max r0.x, r0.y, r0.x
//    4  0x000000FC: sample_l_aoffimmi_indexable(0,-1,0)(texture2d)(float,float,float,float) r0.y, v2.xyxx, t0.xwyz, s0, l(0.000000)
//    5  0x00000134: max r0.x, r0.y, r0.x
//    6  0x00000150: sample_l_aoffimmi_indexable(0,1,0)(texture2d)(float,float,float,float) r0.y, v2.xyxx, t0.xwyz, s0, l(0.000000)
//    7  0x00000188: max r0.x, r0.y, r0.x
//    8  0x000001A4: sample_l_aoffimmi_indexable(-2,0,0)(texture2d)(float,float,float,float) r0.w, v2.xyxx, t0.xyzw, s0, l(0.000000)
//    9  0x000001DC: max r0.w, r0.w, l(0.000000)
//   10  0x000001F8: sample_l_aoffimmi_indexable(2,0,0)(texture2d)(float,float,float,float) r1.x, v2.xyxx, t0.wxyz, s0, l(0.000000)
//   11  0x00000230: max r0.w, r0.w, r1.x
//   12  0x0000024C: sample_l_aoffimmi_indexable(0,-2,0)(texture2d)(float,float,float,float) r1.x, v2.xyxx, t0.wxyz, s0, l(0.000000)
//   13  0x00000284: max r0.w, r0.w, r1.x
//   14  0x000002A0: sample_l_aoffimmi_indexable(0,2,0)(texture2d)(float,float,float,float) r1.x, v2.xyxx, t0.wxyz, s0, l(0.000000)
//   15  0x000002D8: max r0.y, r0.w, r1.x
//   16  0x000002F4: sample_l_aoffimmi_indexable(-1,-1,0)(texture2d)(float,float,float,float) r0.w, v2.xyxx, t0.xyzw, s0, l(0.000000)
//   17  0x0000032C: max r0.w, r0.w, l(0.000000)
//   18  0x00000348: sample_l_aoffimmi_indexable(1,-1,0)(texture2d)(float,float,float,float) r1.x, v2.xyxx, t0.wxyz, s0, l(0.000000)
//   19  0x00000380: max r0.w, r0.w, r1.x
//   20  0x0000039C: sample_l_aoffimmi_indexable(-1,1,0)(texture2d)(float,float,float,float) r1.x, v2.xyxx, t0.wxyz, s0, l(0.000000)
//   21  0x000003D4: max r0.w, r0.w, r1.x
//   22  0x000003F0: sample_l_aoffimmi_indexable(1,1,0)(texture2d)(float,float,float,float) r1.x, v2.xyxx, t0.wxyz, s0, l(0.000000)
//   23  0x00000428: max r0.z, r0.w, r1.x
//   24  0x00000444: mul r0.xyz, r0.xyzx, l(0.900000, 0.600000, 0.800000, 0.000000)
//   25  0x0000046C: sample_l_indexable(texture2d)(float,float,float,float) r0.w, v2.xyxx, t0.xyzw, s0, l(0.000000)
//   26  0x000004A0: max r1.x, r0.w, l(0.000000)
//   27  0x000004BC: mul r1.yzw, r0.wwww, v1.xxyz
//   28  0x000004D8: mul r1.yzw, r1.yyzw, v1.wwww
//   29  0x000004F4: max r0.x, r0.x, r1.x
//   30  0x00000510: max r0.x, r0.y, r0.x
//   31  0x0000052C: max r0.x, r0.z, r0.x
//   32  0x00000548: div o0.xyz, r1.yzwy, r0.xxxx
//   33  0x00000564: mul o0.w, r0.x, v1.w
//   34  0x00000580: ret 
// // Approximately 35 instruction slots used
